#!/bin/bash

if [ -f $HOME/.bash_zaz ]; then
    source $HOME/.bash_zaz
fi

sudo cp $DOTFILES/urxvt/perl_ext/tabbedex/tabbedex /usr/lib/urxvt/perl/tabbedex
sudo patch /usr/lib/urxvt/perl/tabbedex $DOTFILES/urxvt/tabbedexKillTab.patch
#make link 
#ln -s $DOTFILES/urxvt/.urxvtrc $HOME/.urxvtrc