#!/bin/sh


if [ "$(cmus-remote -Q > /dev/null 2 >&1 ; echo $?)" -ne 0 ]; then
#    echo "$(cmus-remote -Q)"
    exit 1;
fi


text=$(cmus-remote -Q)

OUT=$(echo "$text" | grep "tag artist\ " | cut -d ' ' -f 3-)
newline=$(echo "$text" | grep "tag date\ " | cut -d ' ' -f 3-)
OUT=$(echo -e "$OUT\n$newline")
newline=$(echo "$text" | grep "tag album\ " | cut -d ' ' -f 3-)
OUT=$(echo -e "$OUT - $newline")
newline=$(echo "$text" | grep "tag tracknumber\ " | cut -d ' ' -f 3-)
OUT=$(echo -e "$OUT\n$newline")
newline=$(echo "$text" | grep "tag title\ " | cut -d ' ' -f 3-)
OUT=$(echo -e "$OUT  -  $newline")
newline=$(echo "$text" | grep "tag genre\ " | cut -d ' ' -f 3-)
OUT=$(echo -e "$OUT\n$newline")

echo "$OUT"

