#!/usr/bin/env sh

ROWS=$(tput lines)
KOLS=$(tput cols)

RED="88"
KOLOR="15"
PS1=''
for i in $(seq ${ROWS});do  echo -en "$(tput setab ${KOLOR};tput setaf ${KOLOR})\n" ; done
#sleep 3;PS1="$\[{NC}\]>"
for i in $(seq ${ROWS});do  echo -en "$(tput setab ${KOLOR};tput setaf ${KOLOR})\n" ; done
