#!/bin/sh

 if [ -f ~/.bash_zaz ]; then
    source ~/.bash_zaz
 fi



 __printfulline
 __printor "[CLEANING STARTED] at [`__currentTTY`]" $YELLOW
 __printor "[`date -R`]" $YELLOW
 __printfulline


make clean


__printfulline
__printor "[CLEANING DONE] at [`__currentTTY`]" $YELLOW
__printor "[`date -R`]" $YELLOW
__printfulline
