#!/bin/bash

 if [ -f ~/.bash_zaz ]; then
    source ~/.bash_zaz
 fi



 __blockprintor "CLEANING STARTED AT `__currentTTY`" $YELLOW

make clean

__blockprintor "CLEANING DONE AT `__currentTTY`" $GREEN
