#!/bin/sh

if [ -f ~/.bash_zaz ]; then                                                                                                                  
   source ~/.bash_zaz                                                                                                                        
fi 

kek

rm ./core.*
echo  $?
__printor "[rm ./core.*]" $RED
__printor "[`date +%T`]" $RED
