#!/bin/bash


if [ -z "$1" ]; then
    echo
    echo usage: $0 /PATH/TO/FILENAME
    echo
    echo e.g. $0 img.png
    echo
    exit
fi


# if [ -x "exiv2" ]; then
#     kek=
# else
#     echo
#     echo exiv2 not found
#     echo
#     exit
# fi

FILENAME="${1}"


__get_value()
{
    FILE="${1}"
    KEY="${2}"
    echo $(exiv2 -K ${KEY} -pt "${FILE}")
}

__parsedat()
{
    echo "${1}" | sed -E -e "s/([0-9]{1,2})(deg )([0-9]{1,2})('\ )(([0-9]{1,2})(\.)([0-9]{1,3}))(\")/\1 \3 \5/g"
}


## get Latitude
TMP_FIELD="$(__get_value "${FILENAME}" "Exif.GPSInfo.GPSLatitude" )"
LINE="$(echo $TMP_FIELD | cut -d ' ' -f4-)"
LINE=$(__parsedat "${LINE}")

LAT_POLE="$(__get_value "${FILENAME}" "Exif.GPSInfo.GPSLatitudeRef" | awk '{printf $4}' | cut -c 1)"
LAT_DEG="$(echo $LINE | cut -d ' ' -f 1)"
LAT_MIN="$(echo $LINE | cut -d ' ' -f 2)"
LAT_SEC="$(echo $LINE | cut -d ' ' -f 3)"
LAT=${LAT_DEG}"%C2%B0"${LAT_MIN}"'"${LAT_SEC}"%22"${LAT_POLE}


## get Longitude
TMP_FIELD="$(__get_value "${FILENAME}" "Exif.GPSInfo.GPSLongitude" )"
LINE="$(echo $TMP_FIELD | cut -d ' ' -f4-)"
LINE=$(__parsedat "${LINE}")

LON_POLE="$(__get_value "${FILENAME}" "Exif.GPSInfo.GPSLongitudeRef" | awk '{printf $4}' | cut -c 1)"
LON_DEG="$(echo $LINE | cut -d ' ' -f 1)"
LON_MIN="$(echo $LINE | cut -d ' ' -f 2)"
LON_SEC="$(echo $LINE | cut -d ' ' -f 3)"
LON=${LON_DEG}"%C2%B0"${LON_MIN}"'"${LON_SEC}"%22"${LON_POLE}


## make url
URL_BASE="https://www.google.com/maps/place"
URL_OUT=${URL_BASE}"/"${LAT}"+"${LON}

echo $URL_OUT
