#!/bin/sh

COMMAND=${1}

if [ "$(tput colors).." = "8.." ]; then
    myMCFallbackSkin="zaz8"
else
    myMCFallbackSkin="zaz"
fi

shift
## DEBUG
#echo ${COMMAND} --skin $myMCFallbackSkin  $@

## if COMMAND not empty
${COMMAND} --skin $myMCFallbackSkin $@


