#!/bin/bash
#toilet -f future -t "START `date +%T`"

TERMCOLS=$(tput cols)
FULLLINE=$(printf "%-${TERMCOLS}s" "*")
echo "${FULLLINE// /*}"
date
echo "${FULLLINE// /*}"

MKSTARTDATE=$(date +%s)
makek.sh
#toilet -f future -t "STOP  `date +%T`"

MKENDDATE=$(date +%s)

BTMSG="BUILDED IN $((${MKENDDATE} - ${MKSTARTDATE})) SECONDS!"
BTMSGLNGTH=`expr "${BTMSG}" : '.*'`

STARTLINE=$(printf "%-$((${TERMCOLS}/2 - ${BTMSGLNGTH}/2))s" "*")
ENDLINE=$(printf "%-$((${TERMCOLS} - (${TERMCOLS}/2 + ${BTMSGLNGTH}/2)))s" "*")

echo "${FULLLINE// /*}"
echo "${STARTLINE// /*}"`tput setaf 2`${BTMSG}`tput sgr0`"${ENDLINE// /*}"



echo "${FULLLINE// /*}"
echo `date`
echo "${FULLLINE// /*}"
