#!/bin/bash
#toilet -f future -t "START `date +%T`"

if [ -f ~/.bash_zaz ]; then
   source ~/.bash_zaz
fi


__blockprintor "BUILDING STARTED AT `__currentTTY`" $YELLOWFGBG

MKSTARTDATE=$(date +%s)
makek.sh 
#|  sed "s/^/[$YELLOW`date +%T`$NC]/"
RESULT=$?
MKENDDATE=$(date +%s)

if [ $RESULT -eq 0 ]; then
    MKRESULT="BUILDING COMPLETED"
    #COLOR:=${GREEN}

    BTMSG="${MKRESULT} IN $((${MKENDDATE} - ${MKSTARTDATE})) SECONDS!!!"
    __blockprintor "${BTMSG}" ${GREENFGBG}
else
    MKRESULT="BUILDING FAILED"
    #COLOR={$RED}

    BTMSG="${MKRESULT} IN $((${MKENDDATE} - ${MKSTARTDATE})) SECONDS!!!"
    __blockprintor "${BTMSG}" ${REDFGBG}

fi

