#!/bin/bash

if [ -f ~/.bash_zaz ]; then
   source ~/.bash_zaz
fi


__blockprintor "('BUILDING STARTED AT `__currentTTY`','`date -R`')" $YELLOWFGBG

MKSTARTDATE=$(date +%s)
makek.sh
#|  sed "s/^/[$YELLOW`date +%T`$NC]/"
RESULT=$?
MKENDDATE=$(date +%s)

if [ $RESULT -eq 0 ]; then
    MKRESULT="BUILDING COMPLETED"
    #COLOR:=${GREEN}

    BTMSG="${MKRESULT} IN $((${MKENDDATE} - ${MKSTARTDATE})) SECONDS!!!"
    __blockprintor "(${BTMSG},'`date -R`')" ${GREENFGBG}
else
    MKRESULT="BUILDING FAILED"
    #COLOR={$RED}

    BTMSG="${MKRESULT} IN $((${MKENDDATE} - ${MKSTARTDATE})) SECONDS!!!"
    __blockprintor "(${BTMSG},'`date -R`')" ${REDFGBG}

fi

