#!/bin/sh

if [ -f ~/.bash_zaz ]; then
   . ~/.bash_zaz
fi

PRONAME=${2}

#CXXFLAGS_EXT=" -Werror -Wextra -Wall -Weffc++ "

 __msgprintor "PREFIX=$MY_PROJECT_QMAKE_PREFIX" "${YELLOWFGBG}" "qmake"
qmake PREFIX=$MY_PROJECT_QMAKE_PREFIX QMAKE_CXXFLAGS+="-fmax-errors=1${CXXFLAGS_EXT}" CONFIG+=${1} ${PRONAME} && kek "-s" "-j4" && mek "-s" "-j4"
