#!/bin/sh

if [ -f ~/.bash_zaz ]; then
   . ~/.bash_zaz
fi

 __msgprintor "PREFIX=$MY_PROJECT_QMAKE_PREFIX" "${YELLOWFGBG}" "qmake"
qmake PREFIX=$MY_PROJECT_QMAKE_PREFIX CONFIG+=${1} && kek "-s" && mek "-s"
